### ISSUE TITLE
Crashes when opening on 1.19

### ISSUE THREAD

**Issue by la-jig** [Roundaround/mc-fabric-inventory-management#8]
The Game crashes when opened with this mod with fabric saying it needs fabric of any version,
This might be a bug.

**Comment by Roundaround** [comment]
What version do you have installed? And what other mods do you have?

**Comment by la-jig** [comment]
version 1.19 of mod and minecraft and the other mods are:
worldedit-mod-7.2.11-beta-01
replaymod-1.19-2.6.8
OptiFine_1.19_HD_U_H9_MOD
optifabric-1.13.10
modmenu-4.0.4
malilib-fabric-1.19.0-0.13.0
litematica-fabric-1.19.0-0.12.0
lazydfu-0.1.3
FPS-Monitor-1.19-1.2.0-Fabric
fabric-language-kotlin-1.8.3+kotlin.1.7.10
fabric-carpet-1.19-1.4.79+v220607
Essential-fabric_1-19

**Comment by la-jig** [comment]
also the log is:
`
[02:05:02] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.9
[02:05:03] [main/WARN]: Mod resolution failed
[02:05:03] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE inventorymanagement 1.1.0 {depends fabric @ [*]}, ROOT_FORCELOAD_SINGLE inventorymanagement 1.1.0]
[02:05:03] [main/INFO]: Reason: [HARD_DEP inventorymanagement 1.1.0 {depends fabric @ [*]}]
[02:05:03] [main/INFO]: Fix: add [add:fabric 1 ([(-∞,∞)])], remove [], replace []
[02:05:03] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
Unmet dependency listing:
	 - Mod 'Inventory Management' (inventorymanagement) 1.1.0 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
`

**Comment by Roundaround** [comment]
When it is saying you need fabric in this case it's talking about the mod with ID "fabric", which is actually the Fabric API!

https://modrinth.com/mod/fabric-api

**Comment by la-jig** [comment]
ok thank you
